# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /project/
    weight: 20
  - name: Publications
    url: /publication/
    weight: 30
  - name: Team
    url: /people/       # Critical for listing students (CIO requirement)
    weight: 40
  - name: Latest News
    url: /post/       # Critical for listing students (CIO requirement)
    weight: 40
  - name: Gallery
    url: /gallery/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 60